name: Check Markdown links
on:
  pull_request:
    paths:
      - "**.*.md"
  push:
    paths:
      - "**.*.md"
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/*.md
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        if: env.GIT_DIFF
        with:
          folder-path: "."
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/md-link-checker-config.json'
