# This workflow makes a 64 bit Raspberry Pi Arch Linux Image.
# It does not have the security issues mentioned here: https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/running-in-production.md#validator-signing-on-32-bit-architectures-or-arm
# Later, more devices will be supported, as well.

name: Pi Image
on: [push, pull_request]

jobs:
  build:
    name: Starport Pi Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build starport-pi.img with packer-builder-arm
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build .pi/starport.json

      - name: Install PiShrink
        run: |
            wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
            chmod +x pishrink.sh
            sudo mv pishrink.sh /usr/local/bin

      - name: Shrink starport.img
        run: sudo pishrink.sh -Z -v -r -a starport-pi.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Starport PI
          path: starport.img.xz
