name: Publish snap package

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update snapcraft.yaml
        run: |
          make snapcraft version=${GITHUB_REF#refs/tags/}

      - name: Build snap package
        uses: snapcore/action-build@v1
        id: build-snap
        with:
          path: "packaging/snap"

      - name: Publish snap package
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
          snap: ${{ steps.build-snap.outputs.snap }}
          release: stable
